### ISSUE TITLE
Remove legacy configuration support

### ISSUE THREAD

**Issue by Kishi85** [moepman/acertmgr#30]
Remove configuration support for the older /etc/acme/domains.d and /etc/acme directories in 1.0.
Remove support for server_cert, server_key and also the server_ca file config directive.

Always use the CA file provided by the Authority. If no CA data is provided, a prestaged (static) CA should be expected at ca_file.

**Comment by moepman** [comment]
Fixed in ba4dda154bb5b256023ec6d9c464be0f08f3a664
